split_test:
  random_state: 42
  test_size: 0.3
split_val:
  random_state: 42
  test_size: 0.3
text_processing:
  tokenizers:
  - tokenizer_id: Sense
    separator_type: BySense
    lowercasing: 'True'
    token_types:
    - Word
    - Number
    - SentenceBreak
    sub_tokens_policy: SeveralTokens
  - tokenizer_id: Space
    separator_type: ByDelimiter
    lowercasing: 'True'
    delimiter: ' '
  dictionaries:
  - dictionary_id: BiGram
    max_dictionary_size: '50000'
    occurrence_lower_bound: '100'
    gram_order: '2'
  - dictionary_id: Word
    max_dictionary_size: '50000'
    occurrence_lower_bound: '100'
    gram_order: '1'
  - dictionary_id: 3-Gram
    max_dictionary_size: '50000'
    occurrence_lower_bound: '100'
    gram_order: '3'
  feature_processing:
    default:
    - dictionaries_names:
      - BiGram
      - Word
      - 3-Gram
      feature_calcers:
      - BoW
      tokenizers_names:
      - Space
    - dictionaries_names:
      - Word
      - BiGram
      - 3-Gram
      feature_calcers:
      - NaiveBayes
      tokenizers_names:
      - Space
catboost:
  loss_function: 'MultiClass'
  task_type: 'GPU'
  eval_metric: 'TotalF1:average=Macro'
  verbose: 300
  random_seed: 42