stages:
  download:
    cmd: gdown --output datasets/preprocessed_texts.csv https://drive.google.com/u/0/uc?id=1SINqrwjpJOfFxkQDzv4XzoKB3A0A0cws
    outs:
    - datasets/preprocessed_texts.csv
  split_test:
    cmd: python train_test_splitter.py --input datasets/preprocessed_texts.csv
      --output_train datasets/train_test/train.csv --output_test datasets/train_test/test.csv
      --params params.yaml
    deps:
    - datasets/preprocessed_texts.csv
    - train_test_splitter.py
    params:
    - split_test
    outs:
    - datasets/train_test/test.csv
    - datasets/train_test/train.csv
  split_val:
    cmd: python train_val_splitter.py --train datasets/train_test/train.csv --output_train_validate
      datasets/train_val/train.csv --output_val datasets/train_val/val.csv --params params.yaml
    deps:
    - datasets/train_test/train.csv
    - train_val_splitter.py
    params:
    - split_val
    outs:
    - datasets/train_val/val.csv
    - datasets/train_val/train.csv
  objective:
    cmd: python objective_catboost.py --input_train_validate datasets/train_val/train.csv --input_val
      datasets/train_val/val.csv --test datasets/train_test/test.csv --params params.yaml
    deps:
    - datasets/train_val/train.csv
    - datasets/train_val/val.csv
    - objective_catboost.py
    params:
    - text_processing
    - catboost
  train:
    cmd: python best_model.py --input_train_validate datasets/train_val/train.csv --input_val
      datasets/train_val/val.csv --test datasets/train_test/test.csv --params params.yaml
    deps:
    - datasets/train_val/train.csv
    - datasets/train_val/val.csv
    - datasets/train_test/test.csv
    - best_model.py
    params:
    - catboost
    metrics:
    - metrics.json
    outs:
    - catboost_info
